export const Logos = [
    {name: "AAVE", logo: "/logos/aave.png"},
    {name: "AVAX", logo: "/logos/avax.png"},
    {name: "AVE", logo: "/logos/ave.png"},
    {name: "AVME", logo: "/logos/avme.png"},
    {name: "BAG", logo: "/logos/bag.png"},
    {name: "BCH", logo: "/logos/bch.png"},
    {name: "BTC", logo: "/logos/btc.png"},
    {name: "CNR", logo: "/logos/cnr.png"},
    {name: "CYCLE", logo: "/logos/cycle.png"},
    {name: "DREGG", logo: "/logos/dregg.png"},
    {name:"ELA", logo: "/logos/ela.png"},
    {name: "ELK", logo: "/logos/elk.png"},
    {name: "ETH", logo: "/logos/eth.png"},
    {name: "GAJ", logo: "/logos/gaj.png"},
    {name: "GDL", logo: "/logos/gdl.png"},
    {name: "JOE", logo: "/logos/joe.png"},
    {name: "LINK", logo: "/logos/link.png"},
    {name: "LYD", logo: "/logos/lyd.png"},
    {name: "MFI", logo: "/logos/mfi.png"},
    {name: "MIM", logo: "/logos/mim.png"},
    {name: "PEFI", logo: "/logos/pefi.png"},
    {name: "PNG", logo: "/logos/png.png"},
    {name: "QI", logo: "/logos/qi.png"},
    {name: "SNOB", logo: "/logos/snob.png"},
    {name: "SUSHI", logo: "/logos/sushi.png"},
    {name: "TEDDY", logo: "/logos/teddy.png"},
    {name: "wBTC", logo: "/logos/wbtc.png"},
    {name: "XRP", logo: "/logos/xrp.png"},
    {name: "SUSD", logo: "/logos/susd.png"},
    {name: "SET", logo: "/logos/set.png"},
    {name: "USDT", logo: "/logos/usdt.png"},
]