const Logos = {
    aave: "/logos/aave.png",
    avax: "/logos/avax.png",
    ave: "/logos/ave.png",
    avme: "/logos/avme.png",
    bag: "/logos/bag.png",
    bch: "/logos/bch.png",
    btc: "/logos/btc.png",
    cnr: "/logos/cnr.png",
    cycle: "/logos/cycle.png",
    dregg: "/logos/dregg.png",
    ela: "/logos/ela.png",
    elk: "/logos/elk.png",
    eth: "/logos/eth.png",
    gaj: "/logos/gaj.png",
    gdl: "/logos/gdl.png",
    joe: "/logos/joe.png",
    link: "/logos/link.png",
    lyd: "/logos/lyd.png",
    mfi: "/logos/mfi.png",
    mim: "/logos/mim.png",
    pefi: "/logos/pefi.png",
    png: "/logos/png.png",
    qi: "/logos/qi.png",
    snob: "/logos/snob.png",
    set: "/logos/set.png",
    susd: "/logos/susd.png",
    sushi: "/logos/sushi.png",
    teddy: "/logos/teddy.png",
    wbtc: "/logos/wbtc.png",
    xrp: "/logos/xrp.png",
    yts: "/logos/yts.png",
    usdt: "/logos/usdt.png",
}

export default Logos